sudo: required
services:
  - docker

language: php

php:
  - 5.5
  - 5.6
  - 7.0

cache: false

env:
  global:
    - PRODUCT=php-phalcon
  matrix:
    - OS=ubuntu DIST=trusty PACK=deb

matrix:
  fast_finish: true
  allow_failures:
    - env: OS=ubuntu DIST=trusty PACK=deb

script:
  - export PHALCON_VERSION=$(cat cphalcon/CHANGELOG.md | grep -o -m 1 "# \[\([0-9].[0-9].[0-9]\)\]" | sed "s/# \[\([0-9].[0-9].[0-9]\)\]/\1/")
  - export GIT_COMMIT=$(cd cphalcon; git rev-parse --short=8 HEAD)
  - echo -e ${PHALCON_VERSION}
  - echo -e ${GIT_COMMIT}
  - export RELEASE=1
  - export VERSION=${PHALCON_VERSION}-${RELEASE}-${GIT_COMMIT}

  - git clone https://github.com/phalcongelist/build.git
  - build/pack/travis.sh

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
