sudo: required
services:
  - docker

language: php

php:
  - 5.5
  - 5.6
  - 7.0

cache: false

env:
  global:
    - PRODUCT=php-phalcon
  matrix:
    - OS=ubuntu DIST=trusty PACK=deb

matrix:
  fast_finish: true
  allow_failures:
    - env: OS=ubuntu DIST=trusty PACK=deb

script:
  - export VERSION=(cd cphalcon; git describe --long --always | sed -n -e 's/^v\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\1-\2-\3/p')
  - echo $VERSION

  - git clone https://github.com/phalcongelist/build.git
  - build/pack/travis.sh

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
