sudo: required
services:
  - docker

language: php

php:
  - 5.5
  - 5.6
  - 7.0

cache: false

env:
  global:
    - PRODUCT=php-phalcon
    - ENABLED_BRANCHES="master"
    - RELEASE=0
  matrix:
    - OS=ubuntu DIST=trusty PACK=deb PACKAGECLOUD_REPO="phalcon/dist"

matrix:
  fast_finish: true
  allow_failures:
    - env: OS=ubuntu DIST=trusty PACK=deb

before_script:
  - export VERSION=$(cd cphalcon; git describe --long --always | sed -n -e 's/^v\([0-9\.]*\)-\([0-9]*\)-\([a-z0-9]*\)/\1-\2-\3/p')

script:
  - git clone https://github.com/tarantool/build.git
  - build/pack/travis.sh

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
