#  Phalcon Framework
#
#  Copyright (c) 2011-2016, Phalcon Team (https://www.phalconphp.com)
#
#  This source file is subject to the New BSD License that is bundled
#  with this package in the file docs/LICENSE.txt
#
#  If you did not receive a copy of the license and are unable to
#  obtain it through the world-wide-web, please send an email
#  to license@phalconphp.com so we can send you a copy immediately.
#
#  Authors: Andres Gutierrez <andres@phalconphp.com>
#           Serghei Iakovlev <serghei@phalconphp.com>

sudo: required
services:
  - docker

language: php

php:
  - 5.5
  - 5.6
  - 7.0

git:
  depth: 1

cache: false

env:
  global:
    - PRODUCT=php-phalcon
    - RELEASE=$TRAVIS_BUILD_NUMBER
    - STABLE_RELEASE=27
    - PACKAGECLOUD_REPO="phalcon/stable"
    - STABLE_VERSION="v3.0.0"
    - NIGHTLY_VERSION="3.0.x"
    - UPSTREAM_BUILDER="phalcon"
  matrix:
    # Stable versions
    - OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$STABLE_VERSION
    - OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$STABLE_VERSION DOCKER_SUFFIX=7.0 PHP_VERSION=7.0
    - OS=ubuntu DIST=wily PACK=deb PHALCON_VERSION=$STABLE_VERSION
    - OS=ubuntu DIST=xenial PACK=deb PHALCON_VERSION=$STABLE_VERSION
    - OS=debian DIST=jessie PACK=deb PHALCON_VERSION=$STABLE_VERSION
    - OS=debian DIST=stretch PACK=deb PHALCON_VERSION=$STABLE_VERSION
    - PACK=none PHALCON_VERSION=$STABLE_VERSION
    # Nightly versions
    - OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION DOCKER_SUFFIX=7.0 PHP_VERSION=7.0
    - OS=ubuntu DIST=wily PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - OS=ubuntu DIST=xenial PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - OS=debian DIST=jessie PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - OS=debian DIST=stretch PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - PACK=none PHALCON_VERSION=$NIGHTLY_VERSION

# multiple php version exclusion matrix
matrix:
  fast_finish: true
  allow_failures:
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION DOCKER_SUFFIX=7.0 PHP_VERSION=7.0
    - env: OS=ubuntu DIST=wily PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - env: OS=ubuntu DIST=xenial PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - env: OS=debian DIST=jessie PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
    - env: PACK=none PHALCON_VERSION=$NIGHTLY_VERSION
  exclude:
    # Exclude non supported PHP
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$STABLE_VERSION DOCKER_SUFFIX=7.0 PHP_VERSION=7.0
      php: 5.5
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION DOCKER_SUFFIX=7.0 PHP_VERSION=7.0
      php: 5.5
    - env: OS=ubuntu DIST=wily PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 5.5
    - env: OS=ubuntu DIST=wily PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 5.5
    - env: OS=ubuntu DIST=xenial PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 5.5
    - env: OS=ubuntu DIST=xenial PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 5.5
    - env: OS=debian DIST=jessie PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 5.5
    - env: OS=debian DIST=jessie PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 5.5
    - env: OS=debian DIST=stretch PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 5.5
    - env: OS=debian DIST=stretch PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 5.5
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$STABLE_VERSION DOCKER_SUFFIX=7.0 PHP_VERSION=7.0
      php: 5.6
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION DOCKER_SUFFIX=7.0 PHP_VERSION=7.0
      php: 5.6
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 5.6
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 5.6
    - env: OS=ubuntu DIST=xenial PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 5.6
    - env: OS=ubuntu DIST=xenial PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 5.6
    - env: OS=debian DIST=stretch PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 5.6
    - env: OS=debian DIST=stretch PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 5.6
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 7.0
    - env: OS=ubuntu DIST=trusty PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 7.0
    - env: OS=ubuntu DIST=wily PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 7.0
    - env: OS=ubuntu DIST=wily PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 7.0
    - env: OS=debian DIST=jessie PACK=deb PHALCON_VERSION=$STABLE_VERSION
      php: 7.0
    - env: OS=debian DIST=jessie PACK=deb PHALCON_VERSION=$NIGHTLY_VERSION
      php: 7.0

install:
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - '[[ "$TRAVIS_PHP_VERSION" != "7.0" ]] || export ZEND_BACKEND="--backend=ZendEngine3"'
  # TODO: Use common debian/control
  - '[[ "$TRAVIS_PHP_VERSION" == "7.0" ]] || rm debian/control.7.0'
  - '[[ "$TRAVIS_PHP_VERSION" != "7.0" ]] || (rm debian/control && mv debian/control.7.0 debian/control)'
  - '[[ "$PHALCON_VERSION" != $NIGHTLY_VERSION ]] || (bash zephir.sh)'
  - '[[ "$PHALCON_VERSION" != $NIGHTLY_VERSION ]] || (cd cphalcon; zephir fullclean && zephir generate $ZEND_BACKEND)'

before_script:
  - '[[ "$PHALCON_VERSION" != $NIGHTLY_VERSION ]] || export PACKAGECLOUD_REPO="phalcon/nightly"'
  - '[[ "$PHALCON_VERSION" == $NIGHTLY_VERSION ]] || export RELEASE=$STABLE_RELEASE'
  - '[[ -z "$DOCKER_SUFFIX" ]] || export DOCKER_SUFFIX="-${DOCKER_SUFFIX}"'
  - export LAST_COMMIT=$(cd cphalcon; git rev-parse --short=8 HEAD)
  - export PARTIAL_VERSION=$(cd cphalcon; cat config.json | jq ".version" | sed -E 's/\"//g')
  - export VERSION="$PARTIAL_VERSION-$RELEASE-$LAST_COMMIT"

script:
  - git clone -q --depth=1 https://github.com/phalcongelist/build.git -b ${UPSTREAM_BUILDER}
  - build/pack/travis.sh

notifications:
  email:
    recipients:
      - build@phalconphp.com
    on_success: change
    on_failure: always
