#
# Phalcon Build Project
#
# Copyright (c) 2011-2017, Phalcon Team (https://www.phalconphp.com)
#
# This source file is subject to the New BSD License that is bundled
# with this package in the file LICENSE.txt
#
# If you did not receive a copy of the license and are unable to
# obtain it through the world-wide-web, please send an email
# to license@phalconphp.com so we can send you a copy immediately.
#
# Authors: Serghei Iakovlev <serghei@phalconphp.com>
#

sudo: required
dist: trusty

services:
  - docker

language: php

php:
  - 5.5
  - 5.6
  - 7.0

git:
  depth: 1

cache:
  apt: true
  timeout: 691200
  directories:
    - $HOME/.cache

env:
  global:
    - PATH="$HOME/bin:$PATH"
    - PRODUCT=php-phalcon
    # This should be a branch name or a tag
    - STABLE_VERSION=v3.0.4
    - NIGHTLY_VERSION=3.1.x

  matrix:
    # Stable versions
    - OS=el DIST=7 PACKAGE=rpm CLONE_BRANCH=$STABLE_VERSION REPO_VENDOR=ius
    # Nightly versions
    - OS=el DIST=7 PACKAGE=rpm CLONE_BRANCH=$NIGHTLY_VERSION REPO_VENDOR=ius

# multiple php version exclusion matrix
matrix:
  fast_finish: true
  allow_failures:
    - env: OS=el DIST=7 PACKAGE=rpm CLONE_BRANCH=$NIGHTLY_VERSION REPO_VENDOR=ius

before_install:
  - sudo apt-get update -qq
  # Use ZendEngine3 backend for PHP 7.x
  - '[[ "$TRAVIS_PHP_VERSION" != "7.0" ]] || export ZEND_BACKEND="--backend=ZendEngine3"'
  # Disable not needed xdebug
  - phpenv config-rm xdebug.ini || true
  # Create useful symlinks
  - sudo ln -s /home/travis/.phpenv/versions/$(phpenv version-name)/bin/phpize /usr/bin/
  - sudo ln -s /home/travis/.phpenv/versions/$(phpenv version-name)/bin/php-config /usr/bin/

install:
  - sudo apt-get install -y ruby-dev &> /dev/null
  - gem install --no-ri --no-rdoc fpm &> /dev/null
  - bash ./ci/zephir.sh
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${CLONE_BRANCH} $HOME/cphalcon
  # Regenerate build for nightly versions
  - '[[ "$CLONE_BRANCH" != $NIGHTLY_VERSION ]] || bash ./ci/gen-build.sh'

before_script:
  - fpm --version
  - zephir version
  - . ./ci/setup_env_vars.sh

script:
  - make

after_failure:
  - ls -al $HOME

notifications:
  email:
    recipients:
      - build@phalconphp.com
    on_success: change
    on_failure: always
