sudo: required
services:
  - docker

language: php

php:
  - 5.5
  - 5.6
  - 7.0

cache: false

env:
  global:
    - PRODUCT=php-phalcon
    - ENABLED_BRANCHES="master"
    - RELEASE=0
  matrix:
    - OS=ubuntu DIST=trusty PACK=deb PACKAGECLOUD_REPO="phalcon/dist"

matrix:
  fast_finish: true
  allow_failures:
    - env: OS=ubuntu DIST=trusty PACK=deb

before_script:
  - export LAST_COMMIT=$(cd cphalcon; git log -n 1  --pretty=format:"%H" | awk '{print substr($0, 0, 8)}')
  - export PARTIAL_VERSION=$(cd cphalcon; cat config.json | jq ".version")
  - export VERSION="$PARTIAL_VERSION-$RELEASE-$LAST_COMMIT"

script:
  - git clone https://github.com/tarantool/build.git
  - build/pack/travis.sh

notifications:
  email:
    recipients:
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
